-- 정리 및 복습
CREATE TABLE EMP (
	EMPNO NUMBER(4) PRIMARY KEY,
	ENAME VARCHAR(10) NOT NULL,
	JOB VARCHAR2(9),
	HIREDATE DATE,
	SAL NUMBER(7, 2),
	DEPTNO NUMBER(2)
);


-- 뷰는 내일 진행하기로 함
SELECT * FROM EMP;

INSERT INTO EMP VALUES
(1111, '정재현', '무직', SYSDATE, 2100, 10);

--- 뷰 생성
CREATE VIEW EMP_VIEW AS
SELECT EMPNO, ENAME, SAL 
FROM EMP
WHERE SAL > 2000;