-- 제약 사항 이름 붙이고 권한부여해서 테이블을 만들어 봐야한다.
-- 자동증가 시퀸스도 만들기 
-- 데이터 10개 입력

--DROP SEQUENCE MEMBER_SEQ;
--
--
DROP TABLE MEMBER;

-- 시퀀스 생성
CREATE SEQUENCE MEMBER_SEQ 
	START WITH 1
	INCREMENT BY 1
	MAXVALUE 9999999999
	MINVALUE 1
	NOCYCLE;

CREATE TABLE MEMBER (
 	ID NUMBER,
	USERID VARCHAR2(100),
	USERPW VARCHAR2(100) DEFAULT '1234',
	USERNAME VARCHAR2(100) CONSTRAINT MEMBER_USERNAME_NN NOT NULL,
	USEREMAIL VARCHAR2(100) CONSTRAINT MEMBER_USEREMAIL_NNUNIQ NOT NULL UNIQUE,
	CONSTRAINT MEMBER_ID_USERID_PK PRIMARY KEY (ID, USERID)
);

INSERT INTO MEMBER (ID, USERID, USERNAME, USEREMAIL)
VALUES (MEMBER_SEQ.NEXTVAL, 1111, '정재현', 'DEFINEJAE234@GMAIL.COM');
INSERT INTO MEMBER (ID, USERID, USERNAME, USEREMAIL)
VALUES (MEMBER_SEQ.NEXTVAL, 2222, '정다현', 'DEFINEDA234@GMAIL.COM');
INSERT INTO MEMBER (ID, USERID, USERNAME, USEREMAIL)
VALUES (MEMBER_SEQ.NEXTVAL, 3333, '정해영', 'DEFINEHAE234@GMAIL.COM');
INSERT INTO MEMBER (ID, USERID, USERPW, USERNAME, USEREMAIL)
VALUES (MEMBER_SEQ.NEXTVAL, 4444, 4444, '정민희', 'DEFINEMIN234@GMAIL.COM');
--INSERT INTO MEMBER (ID, USERID, USERNAME, USEREMAIL)
--VALUES (MEMBER_SEQ.NEXTVAL, 5555, '정해화', 'DEFINEHAE2234@GMAIL.COM');
--INSERT INTO MEMBER (ID, USERID, USERNAME, USEREMAIL)
--VALUES (MEMBER_SEQ.NEXTVAL, 6666, '정해복', 'DEFINEHAE3234@GMAIL.COM');
--INSERT INTO MEMBER (ID, USERID, USERNAME, USEREMAIL)
--VALUES (MEMBER_SEQ.NEXTVAL, 7777, '임종빈', 'DEFINEJONG5234@GMAIL.COM');
--INSERT INTO MEMBER (ID, USERID, USERNAME, USEREMAIL)
--VALUES (MEMBER_SEQ.NEXTVAL, 8888, '임종훈', 'DEFINEJONG2234@GMAIL.COM');
--INSERT INTO MEMBER (ID, USERID, USERNAME, USEREMAIL)
--VALUES (MEMBER_SEQ.NEXTVAL, 9999, '임하랑', 'DEFINEHA234@GMAIL.COM');
--INSERT INTO MEMBER (ID, USERID, USERNAME, USEREMAIL)
--VALUES (MEMBER_SEQ.NEXTVAL, 10000, '정약용', 'DEFINEYAK234@GMAIL.COM');


SELECT * FROM MEMBER;

delete from member where id='6' AND userID='6666' AND userPW='7777';

SELECT CONSTRAINT_NAME, CONSTRAINT_TYPE, TABLE_NAME
FROM USER_CONSTRAINTS
WHERE TABLE_NAME = 'MEMBER';

-- 왠지 문제에 나올 듯 문자와 숫자로 정의된 COLUMN에서 DESC 갈기면 어떻게 되는지
SELECT * FROM MEMBER
ORDER BY ID DESC;

SELECT * FROM MEMBER
ORDER BY USERID DESC;


update member set userName='정재혀현', userEmail='definejae234@gmail.com' where id=1;

-- 긴급히 COLUMN 항목을 추가해야하는 경우	
ALTER TABLE MEMBER
	ADD USERPW VARCHAR2(100) DEFAULT '1234' CONSTRAINT MEMBER_USERPW_NN NOT NULL;








-- 시퀀스랑 테이블 생성 BOARD SEQ, TABLE
CREATE SEQUENCE BOARD_SEQ 
	START WITH 1
	INCREMENT BY 1
	MAXVALUE 9999999999
	MINVALUE 1
	NOCYCLE;

CREATE TABLE BOARD (
 	ID NUMBER CONSTRAINT BOARD_ID_PK PRIMARY KEY,
	TITLE VARCHAR2(3000) CONSTRAINT BOARD_TITLE_NN NOT NULL,
	CONTENT VARCHAR2(100) CONSTRAINT BOARD_CONTENT_NN NOT NULL,
	WRITER VARCHAR2(100) CONSTRAINT BOARD_WRITER_NN NOT NULL,
	REGDATE DATE DEFAULT SYSDATE,
	HIT NUMBER,
	PASSWORD VARCHAR2(100) 
);

insert into board(id, title, content, writer, regdate, hit, password) values
        (board_seq.nextval, '장발장', '테스트 입니다.', 'TEST USER', SYSDATE, 1, '1234');

SELECT * FROM BOARD;


delete from BOARD where id='2';











