--### 1. 테이블 생성

--`STUDENT` 테이블을 생성하세요.
--
--- 컬럼: 학번(`STUD_ID`) 숫자(4), 이름(`NAME`) 가변문자(20), 학년(`GRADE`) 숫자(1), 입학일(`ADMISSION_DATE`) 날짜형

CREATE TABLE STUDENT (
	STUD_ID NUMBER(4),
	NAME VARCHAR2(20),
	GRADE NUMBER (1),
	ADMISSION_DATE DATE
);

SELECT * FROM STUDENT;


--### 2. 테이블 생성 (다른 예제)

--`BOOK` 테이블을 생성하세요.
--
--- 컬럼: 책번호(`BOOK_ID`) 숫자(5), 제목(`TITLE`) 가변문자(50), 가격(`PRICE`) 숫자(7,2)

CREATE TABLE BOOK (
	BOOK_ID NUMBER(5),
	TITLE VARCHAR2(50),
	PRICE NUMBER(7, 2)
);

SELECT * FROM BOOK;

--### 3. 컬럼 추가
--
--`STUDENT` 테이블에 이메일(`EMAIL`) 컬럼(가변문자 50)을 추가하세요.

ALTER TABLE STUDENT
ADD EMAIL VARCHAR2(50);

SELECT * FROM STUDENT;

--### 4. 컬럼 자료형 변경

--`BOOK` 테이블의 `TITLE` 컬럼 크기를 100자로 변경하세요.
-- 데이터를 바꾸기
ALTER TABLE BOOK
MODIFY TITLE VARCHAR2(100);

SELECT * FROM BOOK;


--### 5. 컬럼 이름 변경
--
--`STUDENT` 테이블의 `NAME` 컬럼을 `STUDENT_NAME` 으로 이름 변경하세요.

ALTER TABLE STUDENT
RENAME COLUMN NAME TO STUDENT_NAME;




--### 6. 컬럼 삭제
--
--`STUDENT` 테이블에서 `GRADE` 컬럼을 삭제하세요.
ALTER TABLE STUDENT 
DROP COLUMN GRADE;

SELECT * FROM STUDENT;

-- ### 7. 테이블 이름 변경

--`BOOK` 테이블의 이름을 `BOOK_INFO` 로 변경하세요.
SELECT * FROM BOOK;
DROP TABLE BOOK;
DROP TABLE BOOK_INFO;

ALTER TABLE BOOK
RENAME TO BOOK_INFO;

SELECT * FROM BOOK_INFO;

--### 8. 테이블 복제

--`STUDENT` 테이블의 구조만 복제하여 `STUDENT_COPY` 테이블을 생성하세요.
DROP TABLE STUDENT_COPY;
CREATE TABLE STUDENT_COPY
AS SELECT * FROM STUDENT WHERE 1 = 0;

SELECT * FROM STUDENT_COPY;

--### 9. 테이블 데이터만 삭제
--
--`STUDENT` 테이블의 모든 데이터를 삭제하되, 구조는 유지하세요.

INSERT INTO STUDENT VALUES
(111, '정재현', SYSDATE, 'DEFINEJAE234@GMAIL.COM');

INSERT INTO STUDENT VALUES
(222, '정다현', SYSDATE, 'DEFINEDA234@GMAIL.COM');

SELECT * FROM STUDENT;
COMMIT;
TRUNCATE TABLE STUDENT;
DELETE STUDENT;
ROLLBACK;

--### 10. 테이블 삭제
--
--`BOOK_INFO` 테이블을 완전히 삭제하세요.
DROP TABLE BOOK_INFO CASCADE CONSTRAINTS;	--- 제약사항

SELECT * FROM BOOK_INFO;

-- 11. STUDENT 데이터들을 STUDENT_COPY 테이블에 모두 복사하시오
SELECT * FROM STUDENT;
SELECT * FROM STUDENT_COPY;
INSERT INTO STUDENT_COPY (SELECT * FROM STUDENT);

DELETE STUDENT_COPY;

DROP TABLE STUDENT;

ALTER TABLE STUDENT_COPY
ADD BIGO VARCHAR2(30);
INSERT INTO STUDENT_COPY (SELECT STUDENT.*, NULL FROM STUDENT);
