-- 1. 부서번호 10의 최소 급여보다 큰 사원의 이름과 급여 부서명을 출력하시오.
-- ENAME, SAL, DEPTNO
SELECT ENAME, SAL, DEPTNO 
FROM EMP
WHERE SAL > (SELECT MIN(SAL) FROM EMP WHERE DEPTNO = 10);

SELECT ENAME, SAL, DEPTNO 
FROM EMP
WHERE SAL > ANY (SELECT SAL FROM EMP WHERE DEPTNO = 10);


-- 2. 자기 부서 평균 급여보다 높은 사원의 이름과 급여 부서번호를 출력하시오.
-- 자기 부서의 평균 급여
SELECT DEPTNO, AVG(SAL)
FROM EMP
GROUP BY DEPTNO;

-- 부서 평균 급여보다 높은 사원 정보 나열
SELECT E1.ENAME, E1.SAL, E1.DEPTNO
FROM EMP E1
WHERE E1.SAL > (SELECT AVG(SAL) FROM EMP GROUP BY DEPTNO HAVING DEPTNO = E1.DEPTNO)
ORDER BY E1.DEPTNO; 

-- 다른 방법?
SELECT EMPNO, ENAME, DEPTNO, SAL
FROM EMP E1
WHERE SAL > (SELECT AVG(SAL) FROM EMP E2 WHERE E2.DEPTNO = E1.DEPTNO)
ORDER BY DEPTNO;


--3. NEW YORK에 근무하는 사원의 이름과 부서 번호를 출력하시오.
SELECT LOC FROM DEPT WHERE LOC = 'NEW YORK';

SELECT E.ENAME, D.DEPTNO
FROM EMP E
JOIN DEPT D ON D.DEPTNO = E.DEPTNO
WHERE D.LOC = 'NEW YORK';

-- 다른 방법
SELECT ENAME, DEPTNO
FROM EMP
WHERE DEPTNO IN (SELECT DEPTNO FROM DEPT WHERE LOC = 'NEW YORK');


--4. SALGRADE 3등급 사원의 이름과 급여 등급을 출력하시오.
SELECT E.ENAME, E.SAL, S.GRADE 
FROM EMP E
JOIN SALGRADE S ON E.SAL BETWEEN S.LOSAL AND S.HISAL
WHERE S.GRADE = 3;

-- 다른 방법
SELECT * FROM SALGRADE WHERE GRADE = 3;

SELECT ENAME, SAL, (SELECT GRADE FROM SALGRADE WHERE E.SAL BETWEEN LOSAL AND HISAL) AS GRADE
FROM EMP E
WHERE (SELECT GRADE FROM SALGRADE WHERE E.SAL BETWEEN LOSAL AND HISAL) = 3;

-- 5. 상사보다 급여가 높은 사원의 이름과 급여 매니저번호를 출력하시오.
SELECT E.ENAME, E.SAL, E.MGR, E2.EMPNO AS MGR_NO, E2.ENAME AS MGR_NAME
FROM EMP E
JOIN EMP E2 ON E2.EMPNO = E.MGR -- EMP E2로 셀프 조인 하여 E2의 EMPNO는 E테이블의 매니저 번호로 저장
WHERE E2.SAL < E.SAL;  -- 매니저 보다 사원이 급여를 더 많이 받는 경우를 추출

-- 만약 JOIN을 안쓰는 경우
SELECT E.ENAME, E.SAL, (SELECT E2.EMPNO FROM EMP E2 WHERE E2.EMPNO = E.MGR AND SAL < E.SAL) AS MGR
FROM EMP E
WHERE (SELECT EMPNO FROM EMP WHERE EMPNO = E.MGR AND SAL < E.SAL) IS NOT NULL;

-- 다른 방법
SELECT E1.ENAME, E1.SAL, E1.MGR 
FROM EMP E1
WHERE E1.SAL > (SELECT SAL FROM EMP E2 WHERE E2.EMPNO = E1.MGR);

SELECT * FROM EMP WHERE MGR = 7839;

--6. 부서별 최고 급여(MAX) 사원의 이름과 급여를 출력하시오.
SELECT MAX(SAL)
FROM EMP
GROUP BY DEPTNO
HAVING DEPTNO = 30; -- 부서 구분 아 혹시 IN 을 써야하나?

SELECT E.DEPTNO, E.ENAME, E.SAL 
FROM EMP E
WHERE E.SAL = 
(SELECT MAX(SAL)
FROM EMP
GROUP BY DEPTNO
HAVING DEPTNO = E.DEPTNO)
ORDER BY DEPTNO;

--- 다른 방법
SELECT DEPTNO, ENAME, SAL 
FROM EMP
WHERE SAL IN (SELECT MAX(SAL) FROM EMP GROUP BY DEPTNO)  -- 복수의 행이 있을 때 사용(최고 급여가 매칭이 되는지 확인)
ORDER BY DEPTNO;

-- 또 다른 방법
SELECT DEPTNO, ENAME, SAL
FROM EMP E
WHERE (DEPTNO, SAL) IN (SELECT DEPTNO, MAX(SAL) FROM EMP GROUP BY DEPTNO);

-- 7. 급여 등급별 사원 수를 출력하시오.
-- SALGRADE를 사용
SELECT S.GRADE, COUNT(*) AS CNT
FROM EMP E
JOIN SALGRADE S ON E.SAL BETWEEN S.LOSAL AND S.HISAL
GROUP BY S.GRADE;

SELECT S.GRADE, E.ENAME
FROM EMP E
JOIN SALGRADE S ON E.SAL BETWEEN S.LOSAL AND S.HISAL

-- 다른방법 서브 쿼리를 사용하는 경우
SELECT GRADE, COUNT(*) AS CNT
FROM ( SELECT
 		(SELECT GRADE FROM SALGRADE S WHERE E.SAL BETWEEN S.LOSAL AND S.HISAL) AS GRADE
		FROM EMP E
		)
GROUP BY GRADE;





--8. 부서 30의 모든 사원보다 급여가 높은 사원의 이름과 급여를 출력하시오. 
SELECT ENAME, SAL
FROM EMP
WHERE SAL > ALL (SELECT SAL FROM EMP WHERE DEPTNO = 30);

SELECT MAX(SAL) FROM EMP WHERE DEPTNO = 30;

