ALTER SESSION SET "_oracle_script" = true;
DROP USER SQLDEV;  -- 계정 삭제
CREATE USER SQLDEV IDENTIFIED BY 1234
DEFAULT TABLESPACE users quota unlimited ON users;
GRANT CREATE SESSION, CREATE TABLE TO SQLDEV;