#spring.application.name=validation
spring:
  application:
    name: validation
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: springjae234
    password: 1234
server:
  port: 8082
