#spring.application.name=practice
spring:
  application:
#    ?? ??????? ??? practice? ??
#    ?? ??, ????, ???? ???? ??? ????? ??
    name: practice
#    ?? ??? ?? ????.?? ? ?? ???? ???? ??
  devtools:
    livereload:
#      livereload??? ???
#      HTML, CSS, JS ??? ???? ????? ???? ??????.
#      ????? LiveReload ????? ???? ??? ??
#      ?? ?????? ? ?? ???? ????;;;
      enabled: true
    restart:
#      ??? ??? ???? ??????? ???? ?????.
#      ?? ? ?? ?? ? ??? ???? ???? ??? ??.
      enabled: true
server:
#  ?? ????? 8082 ???? ??????? ????? ??
#  ???? 8080??? ????? 8082? ??? ??
  port: 8082