#?????...
#spring.application.name=hi
#thymeleaf ?? ??(default)
#???? ??? ???? ?? ???? ??? ???? ?.
#spring.thymeleaf.prefix=classpath:/templates/
#spring.thymeleaf.suffix=.html
#server.port=8081
#server.address=0.0.0.0
#server.address=127.0.0.1

#??? ???? ???? ??? ? ? ??.
spring:
  application:
    name: hi
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
#  thymeleaf:
#    cache: false
server:
  port: 8081

